# Generated by Django 6.0.4 on 2026-04-28 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_category_alter_application_candidate_job_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
    ]
