# Generated by Django 6.0.4 on 2026-04-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_remove_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='missions',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='profile',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
