# Generated by Django 6.0.4 on 2026-04-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_job_missions_job_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='applications/cvs/'),
        ),
        migrations.AddField(
            model_name='application',
            name='full_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='phone',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
