# Generated by Django 6.0.4 on 2026-04-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_application_cv_file_application_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='profile',
            new_name='searched_profile',
        ),
        migrations.AlterField(
            model_name='application',
            name='cv_file',
            field=models.FileField(upload_to='applications/cvs/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='message',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
