# Generated by Django 6.0.4 on 2026-04-28 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0006_rename_profile_job_searched_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='missions',
        ),
        migrations.RemoveField(
            model_name='job',
            name='searched_profile',
        ),
        migrations.CreateModel(
            name='JobMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='careers.job')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JobSearchedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searched_profiles', to='careers.job')),
            ],
            options={
                'verbose_name': 'Searched profile',
                'verbose_name_plural': 'Searched profiles',
                'ordering': ['order', 'id'],
            },
        ),
    ]
