# Generated by Django 6.0.4 on 2026-04-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0007_remove_job_missions_remove_job_searched_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmission',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobsearchedprofile',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
